### ISSUE TITLE
Does not handle import {A as B}

### ISSUE THREAD

**Issue by smhanov** [klesun/ts-browser#14]
bar.ts: 

    export function bar() {
        console.log("bar");
    }

foo.ts:

    import { bar as Bar } from "./bar.ts";

    export function foo() {
        Bar();
    }

Generated code:

    const  { bar as Bar } = window["ts-browser-loaded-modules"]["./bar"];
                 ^^^^^^
Error:

    Uncaught (in promise) SyntaxError: missing : after property id

**Comment by klesun** [comment]
Thanks! Not sure when, but will try to fix.

**Comment by smhanov** [comment]
I got as far as this. But sometimes this function is not called when I tried to test it and I don't understand enough of the other code to figure it out.

    /**
    * @param {ts.ImportClause} importClause - {Field1, Field2}
    */
    const es6ToDestr = (tsCode, importClause) => {
        const { pos, end } = importClause;
        const text = tsCode.slice(pos, end);
        const { namedBindings = null, name = null } = importClause;
        if (namedBindings) {
          const { elements = [], name = null } = namedBindings;
          if (elements.length > 0) {
              // import {A, B, C as Cc} from './module';
              let items = [];
              for (let el of elements) {
                  if (el.propertyName) {
                      // name as propertyName
                      items.push(el.name.escapedText + ": " + el.propertyName.escapedText);
                  } else {
                      // just name
                      items.push(el.name.escapedText);
                  }
              }
              return 'const {' + items.join(", ") + "}";
          } else if (name && name.escapedText) {
              return 'const ' + name.escapedText;
          } else {
              const exc = new Error('Unsupported namedBindings');
              exc.data = { namedBindings, text };
              throw exc;
          }
      } else if (name && name.escapedText) {
          // `import DefaultClass from './module';`
          return 'const {default: ' + text + '}';
      } else {
          const exc = new Error('Unsupported importClause');
          exc.data = { importClause, text };
          throw exc;
      }
  };

**Comment by klesun** [comment]
Oh, if you are willing to dive yourself, I'll try to help you.

Basically, you want to `console.log(namedBindings);` and look what is the data format to which `ts` parses `import { bar as Bar } from ...`.

And then to just add an `else if` branch inside the `if (namedBindings) { ... }`.

(note, when you do `console.log`, you won't see actual text of the AST node, but just `pos, end` - you can use `pos` and `end` to get the actual text of the node using `tsCode.slice(pos, end)`)

A poor man's fix, though, would be to just change:
```typescript
return 'const ' + text;
```
to
```typescript
return 'const ' + text.replace(/\s+as\s+/g, ': ');
```
But, of course, not the best solution.

**Comment by klesun** [comment]
Thanks for the PR, merged, github pages should update in few minutes.
https://github.com/klesun/ts-browser/pull/17

**Comment by klesun** [comment]
Updated npm - [v0.1.1](https://www.npmjs.com/package/ts-browser-klesun/v/0.1.1)

**Comment by klesun** [comment]
Guess I'm closing the issue.
