### ISSUE TITLE
Make it possible to pass options to typescript compiller

### ISSUE THREAD

**Issue by klesun** [klesun/ts-browser#2]
As suggested in #1 should at least make it possible to request compilation to es5. Not sure if will need to change dependency resolver for that...

The usage will be most likely:
```javascript
loadModule('path/to/File.ts'); // load with default settings
loadModule('path/to/File.ts', {
    // ts compiler options
});
```

**Comment by klesun** [comment]
One problem with `jsx` is that react is shipped as CommonJS module, not es6, and this lib does not support CommonJS currently. I'll look if I can tweak it to work with cjs modules too...

**Comment by klesun-misc** [comment]
Works with tsx now. Example:
https://github.com/klesun-misc/ts-browser-react-example
https://klesun-misc.github.io/ts-browser-react-example/

Though still requires manually declaring a es6 module for `react` and `react-dom` for now.

**Comment by Hashbrown777** [comment]
Yeah, I think supporting the various options will either be separate issues or left up to the user that decides to use any specific set of options. Nice work!
