### ISSUE TITLE
Add "mjs" to the Explicit Extensions

### ISSUE THREAD

**Issue by felladrin** [klesun/ts-browser#24]
Thanks for creating TS-Browser!

Could you also add "mjs" to [EXPLICIT_EXTENSIONS](https://github.com/klesun/ts-browser/blob/284439c7518dfba3dab6e94ab82b60a4c8aa0533/src/WorkerManager.js#L4), so we could (inside the loaded .ts file import from .mjs files?)

When I have, for example, `import { init, GameLoop, Sprite } from "https://cdn.jsdelivr.net/npm/kontra@8/kontra.min.mjs";` inside my `index.ts`, it triggers the following error, because it's appending ".ts" to the url/path:
```
[Error: Failed to fetch module file 404: https://cdn.jsdelivr.net/npm/kontra@8/kontra.min.mjs.ts
```
The same happens to relative paths when importing ".mjs" files.

**Comment by klesun** [comment]
Thanks for the feedback. Added `.mjs` to the list in https://github.com/klesun/ts-browser/commit/e8e13764b71e0629e7f08ae998847f959d42d966.
