### ISSUE TITLE
Suggestion: Use JsDelivr CDN instead of GitHub Pages in the Readme example

### ISSUE THREAD

**Issue by felladrin** [klesun/ts-browser#25]
Using the CDN would probably increase reliability.

```html
<!-- index.html -->
<script type="module">
    import { loadModule } from 'https://cdn.jsdelivr.net/gh/klesun/ts-browser/src/ts-browser.js';
    loadModule('./index.ts').then(indexModule => {
        return indexModule.default(document.getElementById('composeCont'));
    });
</script>
```
```typescript
// index.ts
import {makePanel} from './utils/SomeDomMaker';

export default (composeCont) => {
    composeCont.appendChild(makePanel());
};
```

**Comment by klesun** [comment]
Hm, you think jsdelivr is more reliable than github pages? I don't have bases to approve or disprove this assumption...

It's not a perfect measurement of service's performance, of course, but I ran this script right now from Riga, Latvia:

```javascript
var tries = 20;
var jsdelvirTimes = [];
for (let i = 0; i < tries; ++i) {
  const startNs = window.performance.now();
  const body = await fetch("https://cdn.jsdelivr.net/gh/klesun/ts-browser/src/ts-browser.js").then(rs => rs.text());
  jsdelvirTimes.push(window.performance.now() - startNs);
}
const githubTimes = [];
for (let i = 0; i < tries; ++i) {
  const startNs = window.performance.now();
  const body = await fetch("https://klesun.github.io/ts-browser/src/ts-browser.js").then(rs => rs.text());
  githubTimes.push(window.performance.now() - startNs);
}
console.log("jsdelvirTimes: " + jsdelvirTimes.reduce((a,b) => a + b) / tries);
console.log("githubTimes: " + githubTimes.reduce((a,b) => a + b) / tries);
```

![image](https://user-images.githubusercontent.com/5202330/158803260-60192450-fdd5-4dca-b40a-821ec042938b.png)

![image](https://user-images.githubusercontent.com/5202330/158803328-b2b77fc5-085f-4c69-b9a7-911d061ad4b8.png)

![image](https://user-images.githubusercontent.com/5202330/158803394-7ae36d56-dc1c-4610-9847-7501dc54d707.png)

Github Pages seems to reply slightly faster in this part of the world. Guess microsoft does not spare funds on their datacenters either.

So I guess I close this issue, unless there is something that I'm missing about Github Pages vs JsDelvir
