### ISSUE TITLE
Does this library work with dynamic imports?

### ISSUE THREAD

**Issue by ashmind** [klesun/ts-browser#5]
E.g. something like this
```
import('./levels/1');
```
produces
```
./js/test.ts:1 Uncaught (in promise) TypeError: Failed to resolve module specifier './levels/1'
    at ./js/test.ts:1
```

While `import x from './levels/1'` works as expected.

**Comment by klesun** [comment]
Dynamic imports are not supported by the lib currently. I consider adding them in future, though.

**Comment by klesun** [comment]
I added a basic support for dynamic imports in the [beta](https://github.com/klesun-misc/ts-browser-beta) repo, you can use it with this url:
```javascript
import {loadModule} from 'https://klesun-misc.github.io/ts-browser-beta/src/ts-browser.js';
```

Did not test it much, so any feedback, failing cornercases are very very welcome.

**Comment by ashmind** [comment]
@klesun Thanks!
Seems like `await import(...)`  generates `awaitwindow["ts-browser-import-dynamic"](...)` -- missing space after `await`.

**Comment by klesun** [comment]
oh, lol, thanks, sorry, will fix in few minutes

**Comment by klesun** [comment]
Fixed that - https://github.com/klesun-misc/ts-browser-beta/commit/090f69ed8d3ab7e799b683530e6a69d5ebb7b38c

**Comment by ashmind** [comment]
Thanks! I _think_ there is another issue, with relative path resolution.

I am calling import from `/ts/app.ts` and importing `./levels/${levelNumber}` which is relative to `/ts/app.ts`. In my understanding, it should import from `/ts/levels/1.ts`, but it seems to be `/levels/1.ts` (ignoring the current file path).

**Comment by klesun** [comment]
yeah, thanks, good point, on it

**Comment by klesun** [comment]
Fixed that - https://github.com/klesun-misc/ts-browser-beta/commit/d05663392427e136b4c23691ed13510021a12795

**Comment by ashmind** [comment]
Awesome, it works now! Thanks a lot!

**Comment by klesun** [comment]
Added few performance fixes, merged into main repo. Seems to work ok.
